-- ================================================================
-- MITRA CBT — Seed 25 soal GTO (Gambar Teknik Otomotif) asli
-- Auto-generated by scripts/generate-gto-seed-sql.mjs — JANGAN edit manual.
-- Jalankan SETELAH schema.sql & seed.sql, di: Supabase → SQL Editor
-- Idempotent: aman dijalankan berulang kali (ON CONFLICT DO UPDATE).
-- ================================================================

INSERT INTO public.question_banks (id, teacher_id, subject_id, title, description, target_grades)
VALUES (
  '55555555-5555-5555-5555-555555555001',
  (SELECT id FROM public.teachers WHERE nip = '198506152010011012'),
  '33333333-3333-3333-3333-333333333001',
  'Bank Soal Komprehensif Gambar Teknik Otomotif Kelas X',
  'Kumpulan soal standar ISO untuk proyeksi, etiket, garis kerja, dan potongan mesin.',
  ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  teacher_id  = EXCLUDED.teacher_id,
  subject_id  = EXCLUDED.subject_id,
  title       = EXCLUDED.title,
  description = EXCLUDED.description,
  target_grades = EXCLUDED.target_grades;

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000001', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Fungsi utama gambar teknik dalam bidang otomotif adalah...', 'Gambar teknik digunakan sebagai media komunikasi untuk menyampaikan bentuk, ukuran, dan informasi teknis suatu benda.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000001';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000001000001', '66666666-6666-6666-6666-000000000001', 'A', 'Sebagai gambar hiasan', FALSE, 1),
  ('77777777-7777-7777-7777-000001000002', '66666666-6666-6666-6666-000000000001', 'B', 'Sebagai media komunikasi teknik', TRUE, 2),
  ('77777777-7777-7777-7777-000001000003', '66666666-6666-6666-6666-000000000001', 'C', 'Sebagai media promosi kendaraan', FALSE, 3),
  ('77777777-7777-7777-7777-000001000004', '66666666-6666-6666-6666-000000000001', 'D', 'Sebagai gambar bebas', FALSE, 4),
  ('77777777-7777-7777-7777-000001000005', '66666666-6666-6666-6666-000000000001', 'E', 'Sebagai penentu harga kendaraan', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000002', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Alat yang digunakan untuk membuat garis lurus pada gambar teknik adalah...', 'Penggaris digunakan untuk membuat garis lurus dengan rapi dan sesuai kebutuhan gambar.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000002';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000002000001', '66666666-6666-6666-6666-000000000002', 'A', 'Jangka', FALSE, 1),
  ('77777777-7777-7777-7777-000002000002', '66666666-6666-6666-6666-000000000002', 'B', 'Penggaris', TRUE, 2),
  ('77777777-7777-7777-7777-000002000003', '66666666-6666-6666-6666-000000000002', 'C', 'Busur derajat', FALSE, 3),
  ('77777777-7777-7777-7777-000002000004', '66666666-6666-6666-6666-000000000002', 'D', 'Mal lingkaran', FALSE, 4),
  ('77777777-7777-7777-7777-000002000005', '66666666-6666-6666-6666-000000000002', 'E', 'Penghapus', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000003', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Alat gambar yang digunakan untuk membuat lingkaran adalah...', 'Jangka digunakan untuk membuat bentuk lingkaran dengan ukuran radius tertentu.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000003';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000003000001', '66666666-6666-6666-6666-000000000003', 'A', 'Penggaris', FALSE, 1),
  ('77777777-7777-7777-7777-000003000002', '66666666-6666-6666-6666-000000000003', 'B', 'Siku', FALSE, 2),
  ('77777777-7777-7777-7777-000003000003', '66666666-6666-6666-6666-000000000003', 'C', 'Jangka', TRUE, 3),
  ('77777777-7777-7777-7777-000003000004', '66666666-6666-6666-6666-000000000003', 'D', 'Mal huruf', FALSE, 4),
  ('77777777-7777-7777-7777-000003000005', '66666666-6666-6666-6666-000000000003', 'E', 'Penghapus', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000004', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Pensil dengan kode H memiliki karakteristik...', 'Pensil H memiliki karakteristik lebih keras sehingga cocok digunakan untuk garis tipis dan garis bantu.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000004';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000004000001', '66666666-6666-6666-6666-000000000004', 'A', 'Lunak dan sangat hitam', FALSE, 1),
  ('77777777-7777-7777-7777-000004000002', '66666666-6666-6666-6666-000000000004', 'B', 'Keras dan menghasilkan garis tipis', TRUE, 2),
  ('77777777-7777-7777-7777-000004000003', '66666666-6666-6666-6666-000000000004', 'C', 'Tidak dapat digunakan menggambar', FALSE, 3),
  ('77777777-7777-7777-7777-000004000004', '66666666-6666-6666-6666-000000000004', 'D', 'Digunakan untuk menghapus', FALSE, 4),
  ('77777777-7777-7777-7777-000004000005', '66666666-6666-6666-6666-000000000004', 'E', 'Digunakan untuk membuat arsiran tebal', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000005', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Pensil dengan kode B biasanya menghasilkan garis yang...', 'Pensil B lebih lunak dan menghasilkan garis yang lebih hitam dibandingkan pensil H.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000005';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000005000001', '66666666-6666-6666-6666-000000000005', 'A', 'Tipis dan samar', FALSE, 1),
  ('77777777-7777-7777-7777-000005000002', '66666666-6666-6666-6666-000000000005', 'B', 'Lebih hitam dan lunak', TRUE, 2),
  ('77777777-7777-7777-7777-000005000003', '66666666-6666-6666-6666-000000000005', 'C', 'Tidak terlihat', FALSE, 3),
  ('77777777-7777-7777-7777-000005000004', '66666666-6666-6666-6666-000000000005', 'D', 'Selalu putus-putus', FALSE, 4),
  ('77777777-7777-7777-7777-000005000005', '66666666-6666-6666-6666-000000000005', 'E', 'Tidak dapat dihapus', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000006', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Garis kontinu tebal pada gambar teknik umumnya digunakan untuk menunjukkan...', 'Garis kontinu tebal digunakan untuk menggambarkan sisi atau bagian benda yang terlihat.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000006';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000006000001', '66666666-6666-6666-6666-000000000006', 'A', 'Bagian benda yang terlihat', TRUE, 1),
  ('77777777-7777-7777-7777-000006000002', '66666666-6666-6666-6666-000000000006', 'B', 'Bagian benda yang tersembunyi', FALSE, 2),
  ('77777777-7777-7777-7777-000006000003', '66666666-6666-6666-6666-000000000006', 'C', 'Garis sumbu', FALSE, 3),
  ('77777777-7777-7777-7777-000006000004', '66666666-6666-6666-6666-000000000006', 'D', 'Garis ukuran', FALSE, 4),
  ('77777777-7777-7777-7777-000006000005', '66666666-6666-6666-6666-000000000006', 'E', 'Garis bantu', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000007', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Garis putus-putus pada gambar teknik digunakan untuk menunjukkan...', 'Garis putus-putus digunakan untuk menunjukkan bagian benda yang berada di belakang atau tidak terlihat.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000007';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000007000001', '66666666-6666-6666-6666-000000000007', 'A', 'Bagian benda yang terlihat', FALSE, 1),
  ('77777777-7777-7777-7777-000007000002', '66666666-6666-6666-6666-000000000007', 'B', 'Bagian benda yang tidak terlihat', TRUE, 2),
  ('77777777-7777-7777-7777-000007000003', '66666666-6666-6666-6666-000000000007', 'C', 'Garis ukuran', FALSE, 3),
  ('77777777-7777-7777-7777-000007000004', '66666666-6666-6666-6666-000000000007', 'D', 'Garis sumbu', FALSE, 4),
  ('77777777-7777-7777-7777-000007000005', '66666666-6666-6666-6666-000000000007', 'E', 'Garis potongan', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000008', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Garis sumbu pada gambar teknik berfungsi untuk menunjukkan...', 'Garis sumbu digunakan untuk menunjukkan pusat lingkaran, sumbu simetri, atau sumbu suatu komponen.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000008';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000008000001', '66666666-6666-6666-6666-000000000008', 'A', 'Ukuran benda', FALSE, 1),
  ('77777777-7777-7777-7777-000008000002', '66666666-6666-6666-6666-000000000008', 'B', 'Pusat atau sumbu benda', TRUE, 2),
  ('77777777-7777-7777-7777-000008000003', '66666666-6666-6666-6666-000000000008', 'C', 'Bagian benda yang dipotong', FALSE, 3),
  ('77777777-7777-7777-7777-000008000004', '66666666-6666-6666-6666-000000000008', 'D', 'Tebal benda', FALSE, 4),
  ('77777777-7777-7777-7777-000008000005', '66666666-6666-6666-6666-000000000008', 'E', 'Permukaan benda', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000009', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Etiket pada gambar teknik berfungsi untuk memberikan...', 'Etiket berisi informasi gambar seperti nama gambar, nama pembuat, skala, nomor gambar, dan informasi lainnya.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000009';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000009000001', '66666666-6666-6666-6666-000000000009', 'A', 'Warna pada gambar', FALSE, 1),
  ('77777777-7777-7777-7777-000009000002', '66666666-6666-6666-6666-000000000009', 'B', 'Identitas dan informasi gambar', TRUE, 2),
  ('77777777-7777-7777-7777-000009000003', '66666666-6666-6666-6666-000000000009', 'C', 'Efek tiga dimensi', FALSE, 3),
  ('77777777-7777-7777-7777-000009000004', '66666666-6666-6666-6666-000000000009', 'D', 'Hiasan gambar', FALSE, 4),
  ('77777777-7777-7777-7777-000009000005', '66666666-6666-6666-6666-000000000009', 'E', 'Arsiran benda', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000010', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Salah satu informasi yang terdapat pada etiket gambar adalah...', 'Nama gambar merupakan salah satu informasi penting yang dicantumkan pada etiket.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000010';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000010000001', '66666666-6666-6666-6666-000000000010', 'A', 'Nama gambar', TRUE, 1),
  ('77777777-7777-7777-7777-000010000002', '66666666-6666-6666-6666-000000000010', 'B', 'Warna kendaraan', FALSE, 2),
  ('77777777-7777-7777-7777-000010000003', '66666666-6666-6666-6666-000000000010', 'C', 'Harga kendaraan', FALSE, 3),
  ('77777777-7777-7777-7777-000010000004', '66666666-6666-6666-6666-000000000010', 'D', 'Nama pemilik kendaraan', FALSE, 4),
  ('77777777-7777-7777-7777-000010000005', '66666666-6666-6666-6666-000000000010', 'E', 'Nomor mesin kendaraan', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000011', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Ukuran kertas gambar A4 adalah...', 'Ukuran standar kertas A4 adalah 210 × 297 mm.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000011';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000011000001', '66666666-6666-6666-6666-000000000011', 'A', '148 × 210 mm', FALSE, 1),
  ('77777777-7777-7777-7777-000011000002', '66666666-6666-6666-6666-000000000011', 'B', '210 × 297 mm', TRUE, 2),
  ('77777777-7777-7777-7777-000011000003', '66666666-6666-6666-6666-000000000011', 'C', '297 × 420 mm', FALSE, 3),
  ('77777777-7777-7777-7777-000011000004', '66666666-6666-6666-6666-000000000011', 'D', '420 × 594 mm', FALSE, 4),
  ('77777777-7777-7777-7777-000011000005', '66666666-6666-6666-6666-000000000011', 'E', '594 × 841 mm', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000012', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Skala 1 : 2 pada gambar teknik berarti...', 'Skala 1:2 berarti setiap 1 satuan pada gambar mewakili 2 satuan ukuran sebenarnya.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000012';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000012000001', '66666666-6666-6666-6666-000000000012', 'A', 'Gambar dua kali lebih besar dari benda', FALSE, 1),
  ('77777777-7777-7777-7777-000012000002', '66666666-6666-6666-6666-000000000012', 'B', 'Gambar sama besar dengan benda', FALSE, 2),
  ('77777777-7777-7777-7777-000012000003', '66666666-6666-6666-6666-000000000012', 'C', 'Gambar setengah dari ukuran sebenarnya', TRUE, 3),
  ('77777777-7777-7777-7777-000012000004', '66666666-6666-6666-6666-000000000012', 'D', 'Benda setengah dari ukuran gambar', FALSE, 4),
  ('77777777-7777-7777-7777-000012000005', '66666666-6666-6666-6666-000000000012', 'E', 'Gambar tidak memiliki ukuran', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000013', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Sebuah komponen memiliki panjang sebenarnya 100 mm. Jika digambar dengan skala 1:2, panjang pada gambar adalah...', 'Skala 1:2 berarti ukuran gambar adalah setengah dari ukuran sebenarnya. Jadi 100 mm ÷ 2 = 50 mm.',
  2, 'sedang', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000013';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000013000001', '66666666-6666-6666-6666-000000000013', 'A', '25 mm', FALSE, 1),
  ('77777777-7777-7777-7777-000013000002', '66666666-6666-6666-6666-000000000013', 'B', '40 mm', FALSE, 2),
  ('77777777-7777-7777-7777-000013000003', '66666666-6666-6666-6666-000000000013', 'C', '50 mm', TRUE, 3),
  ('77777777-7777-7777-7777-000013000004', '66666666-6666-6666-6666-000000000013', 'D', '100 mm', FALSE, 4),
  ('77777777-7777-7777-7777-000013000005', '66666666-6666-6666-6666-000000000013', 'E', '200 mm', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000014', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Skala 2 : 1 menunjukkan bahwa gambar dibuat...', 'Skala 2:1 merupakan skala pembesaran, sehingga ukuran gambar dua kali ukuran benda sebenarnya.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000014';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000014000001', '66666666-6666-6666-6666-000000000014', 'A', 'Setengah dari ukuran sebenarnya', FALSE, 1),
  ('77777777-7777-7777-7777-000014000002', '66666666-6666-6666-6666-000000000014', 'B', 'Sama dengan ukuran sebenarnya', FALSE, 2),
  ('77777777-7777-7777-7777-000014000003', '66666666-6666-6666-6666-000000000014', 'C', 'Dua kali ukuran sebenarnya', TRUE, 3),
  ('77777777-7777-7777-7777-000014000004', '66666666-6666-6666-6666-000000000014', 'D', 'Tiga kali ukuran sebenarnya', FALSE, 4),
  ('77777777-7777-7777-7777-000014000005', '66666666-6666-6666-6666-000000000014', 'E', 'Tanpa ukuran', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000015', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Pandangan benda yang dilihat dari arah depan disebut...', 'Pandangan depan merupakan gambar benda yang dilihat dari arah depan.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000015';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000015000001', '66666666-6666-6666-6666-000000000015', 'A', 'Pandangan atas', FALSE, 1),
  ('77777777-7777-7777-7777-000015000002', '66666666-6666-6666-6666-000000000015', 'B', 'Pandangan depan', TRUE, 2),
  ('77777777-7777-7777-7777-000015000003', '66666666-6666-6666-6666-000000000015', 'C', 'Pandangan samping', FALSE, 3),
  ('77777777-7777-7777-7777-000015000004', '66666666-6666-6666-6666-000000000015', 'D', 'Pandangan belakang', FALSE, 4),
  ('77777777-7777-7777-7777-000015000005', '66666666-6666-6666-6666-000000000015', 'E', 'Pandangan bawah', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000016', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Pandangan atas digunakan untuk memperlihatkan bentuk benda dari arah...', 'Pandangan atas menunjukkan bentuk benda ketika dilihat dari arah atas.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000016';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000016000001', '66666666-6666-6666-6666-000000000016', 'A', 'Depan', FALSE, 1),
  ('77777777-7777-7777-7777-000016000002', '66666666-6666-6666-6666-000000000016', 'B', 'Belakang', FALSE, 2),
  ('77777777-7777-7777-7777-000016000003', '66666666-6666-6666-6666-000000000016', 'C', 'Atas', TRUE, 3),
  ('77777777-7777-7777-7777-000016000004', '66666666-6666-6666-6666-000000000016', 'D', 'Bawah', FALSE, 4),
  ('77777777-7777-7777-7777-000016000005', '66666666-6666-6666-6666-000000000016', 'E', 'Samping', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000017', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Penggunaan beberapa pandangan dalam gambar teknik bertujuan untuk...', 'Beberapa pandangan digunakan agar bentuk dan detail benda dapat dipahami secara lengkap.',
  2, 'sedang', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000017';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000017000001', '66666666-6666-6666-6666-000000000017', 'A', 'Memperindah gambar', FALSE, 1),
  ('77777777-7777-7777-7777-000017000002', '66666666-6666-6666-6666-000000000017', 'B', 'Menunjukkan bentuk benda secara lebih lengkap', TRUE, 2),
  ('77777777-7777-7777-7777-000017000003', '66666666-6666-6666-6666-000000000017', 'C', 'Mengurangi ukuran benda', FALSE, 3),
  ('77777777-7777-7777-7777-000017000004', '66666666-6666-6666-6666-000000000017', 'D', 'Menghilangkan garis benda', FALSE, 4),
  ('77777777-7777-7777-7777-000017000005', '66666666-6666-6666-6666-000000000017', 'E', 'Mengurangi informasi gambar', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000018', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Gambar yang memperlihatkan panjang, lebar, dan tinggi benda disebut gambar...', 'Gambar 3D menampilkan tiga dimensi benda, yaitu panjang, lebar, dan tinggi.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000018';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000018000001', '66666666-6666-6666-6666-000000000018', 'A', '1D', FALSE, 1),
  ('77777777-7777-7777-7777-000018000002', '66666666-6666-6666-6666-000000000018', 'B', '2D', FALSE, 2),
  ('77777777-7777-7777-7777-000018000003', '66666666-6666-6666-6666-000000000018', 'C', '3D', TRUE, 3),
  ('77777777-7777-7777-7777-000018000004', '66666666-6666-6666-6666-000000000018', 'D', 'Simbol', FALSE, 4),
  ('77777777-7777-7777-7777-000018000005', '66666666-6666-6666-6666-000000000018', 'E', 'Sketsa', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000019', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Fungsi garis ukuran pada gambar teknik adalah...', 'Garis ukuran digunakan bersama angka ukuran untuk menunjukkan dimensi suatu bagian benda.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000019';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000019000001', '66666666-6666-6666-6666-000000000019', 'A', 'Menunjukkan bagian tersembunyi', FALSE, 1),
  ('77777777-7777-7777-7777-000019000002', '66666666-6666-6666-6666-000000000019', 'B', 'Menunjukkan ukuran benda', TRUE, 2),
  ('77777777-7777-7777-7777-000019000003', '66666666-6666-6666-6666-000000000019', 'C', 'Menunjukkan pusat benda', FALSE, 3),
  ('77777777-7777-7777-7777-000019000004', '66666666-6666-6666-6666-000000000019', 'D', 'Menunjukkan warna benda', FALSE, 4),
  ('77777777-7777-7777-7777-000019000005', '66666666-6666-6666-6666-000000000019', 'E', 'Menunjukkan bahan benda', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000020', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Tanda anak panah pada garis ukuran menunjukkan...', 'Anak panah pada garis ukuran menunjukkan batas atau titik awal dan akhir ukuran yang diberikan.',
  2, 'sedang', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000020';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000020000001', '66666666-6666-6666-6666-000000000020', 'A', 'Arah pandangan', FALSE, 1),
  ('77777777-7777-7777-7777-000020000002', '66666666-6666-6666-6666-000000000020', 'B', 'Batas ukuran', TRUE, 2),
  ('77777777-7777-7777-7777-000020000003', '66666666-6666-6666-6666-000000000020', 'C', 'Pusat benda', FALSE, 3),
  ('77777777-7777-7777-7777-000020000004', '66666666-6666-6666-6666-000000000020', 'D', 'Bagian tersembunyi', FALSE, 4),
  ('77777777-7777-7777-7777-000020000005', '66666666-6666-6666-6666-000000000020', 'E', 'Bagian yang dipotong', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000021', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Gambar potongan digunakan untuk memperlihatkan...', 'Gambar potongan digunakan untuk memperjelas bentuk dan konstruksi bagian dalam suatu benda.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000021';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000021000001', '66666666-6666-6666-6666-000000000021', 'A', 'Warna benda', FALSE, 1),
  ('77777777-7777-7777-7777-000021000002', '66666666-6666-6666-6666-000000000021', 'B', 'Bagian dalam benda', TRUE, 2),
  ('77777777-7777-7777-7777-000021000003', '66666666-6666-6666-6666-000000000021', 'C', 'Harga benda', FALSE, 3),
  ('77777777-7777-7777-7777-000021000004', '66666666-6666-6666-6666-000000000021', 'D', 'Ukuran kertas', FALSE, 4),
  ('77777777-7777-7777-7777-000021000005', '66666666-6666-6666-6666-000000000021', 'E', 'Nama pembuat', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000022', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Arsiran pada gambar potongan menunjukkan bagian benda yang...', 'Arsiran digunakan untuk menunjukkan permukaan atau bagian benda yang terkena bidang potong.',
  2, 'sedang', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000022';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000022000001', '66666666-6666-6666-6666-000000000022', 'A', 'Tidak terkena potongan', FALSE, 1),
  ('77777777-7777-7777-7777-000022000002', '66666666-6666-6666-6666-000000000022', 'B', 'Terkena bidang potong', TRUE, 2),
  ('77777777-7777-7777-7777-000022000003', '66666666-6666-6666-6666-000000000022', 'C', 'Tidak terlihat', FALSE, 3),
  ('77777777-7777-7777-7777-000022000004', '66666666-6666-6666-6666-000000000022', 'D', 'Berputar', FALSE, 4),
  ('77777777-7777-7777-7777-000022000005', '66666666-6666-6666-6666-000000000022', 'E', 'Bergerak', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000023', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Dalam AutoCAD, perintah LINE digunakan untuk...', 'Perintah LINE pada AutoCAD digunakan untuk membuat objek berupa garis lurus.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000023';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000023000001', '66666666-6666-6666-6666-000000000023', 'A', 'Membuat lingkaran', FALSE, 1),
  ('77777777-7777-7777-7777-000023000002', '66666666-6666-6666-6666-000000000023', 'B', 'Membuat garis', TRUE, 2),
  ('77777777-7777-7777-7777-000023000003', '66666666-6666-6666-6666-000000000023', 'C', 'Menghapus objek', FALSE, 3),
  ('77777777-7777-7777-7777-000023000004', '66666666-6666-6666-6666-000000000023', 'D', 'Membuat teks', FALSE, 4),
  ('77777777-7777-7777-7777-000023000005', '66666666-6666-6666-6666-000000000023', 'E', 'Memindahkan objek', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000024', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Dalam AutoCAD, perintah CIRCLE digunakan untuk membuat...', 'Perintah CIRCLE digunakan untuk membuat objek lingkaran dengan menentukan titik pusat dan radius atau diameter.',
  2, 'mudah', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000024';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000024000001', '66666666-6666-6666-6666-000000000024', 'A', 'Garis', FALSE, 1),
  ('77777777-7777-7777-7777-000024000002', '66666666-6666-6666-6666-000000000024', 'B', 'Persegi', FALSE, 2),
  ('77777777-7777-7777-7777-000024000003', '66666666-6666-6666-6666-000000000024', 'C', 'Lingkaran', TRUE, 3),
  ('77777777-7777-7777-7777-000024000004', '66666666-6666-6666-6666-000000000024', 'D', 'Teks', FALSE, 4),
  ('77777777-7777-7777-7777-000024000005', '66666666-6666-6666-6666-000000000024', 'E', 'Arsiran', FALSE, 5);

INSERT INTO public.questions (id, bank_id, material_id, question_type, content, explanation, weight, difficulty, competency, created_at, target_grades)
VALUES (
  '66666666-6666-6666-6666-000000000025', '55555555-5555-5555-5555-555555555001', '44444444-4444-4444-4444-444444444001',
  'pilihan_ganda', 'Dalam pembuatan gambar teknik, ketelitian ukuran sangat penting karena...', 'Ketelitian ukuran sangat penting agar hasil pembuatan atau pengerjaan benda sesuai dengan rancangan yang telah dibuat.',
  2, 'sedang', 'Mengidentifikasi peralatan dan standar gambar teknik otomotif', '2024-09-01T08:00:00Z', ARRAY['X']
)
ON CONFLICT (id) DO UPDATE SET
  bank_id      = EXCLUDED.bank_id,
  material_id  = EXCLUDED.material_id,
  question_type = EXCLUDED.question_type,
  content      = EXCLUDED.content,
  explanation  = EXCLUDED.explanation,
  weight       = EXCLUDED.weight,
  difficulty   = EXCLUDED.difficulty,
  competency   = EXCLUDED.competency,
  target_grades = EXCLUDED.target_grades;

DELETE FROM public.question_options WHERE question_id = '66666666-6666-6666-6666-000000000025';
INSERT INTO public.question_options (id, question_id, option_label, content, is_correct, order_index) VALUES
  ('77777777-7777-7777-7777-000025000001', '66666666-6666-6666-6666-000000000025', 'A', 'Agar gambar terlihat lebih berwarna', FALSE, 1),
  ('77777777-7777-7777-7777-000025000002', '66666666-6666-6666-6666-000000000025', 'B', 'Agar benda dapat dibuat sesuai rancangan', TRUE, 2),
  ('77777777-7777-7777-7777-000025000003', '66666666-6666-6666-6666-000000000025', 'C', 'Agar kertas tidak cepat rusak', FALSE, 3),
  ('77777777-7777-7777-7777-000025000004', '66666666-6666-6666-6666-000000000025', 'D', 'Agar gambar menjadi lebih besar', FALSE, 4),
  ('77777777-7777-7777-7777-000025000005', '66666666-6666-6666-6666-000000000025', 'E', 'Agar gambar lebih sulit dibaca', FALSE, 5);

